version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: hp_nginx
    depends_on:
      - php
      - mysql
    ports:
      - "8081:80"
    volumes:
      - ../hapoLearn:/var/www/html
      - ./.deployment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hapo-network
  php:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../hapoLearn:/var/www/html
    container_name: hp_app
    ports:
      - "9000:9000"
    networks:
      - hapo-network
  mysql:
    image: mysql:8.0.32
    restart: always
    container_name: hp_mysql
    tty: true
    ports:
      - "3309:3306"
    volumes:
      - ./.deployment/mysql:/var/lib/mysql
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_DATABASE: hapo_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12341234a
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - hapo-network

networks:
  hapo-network:
    driver: bridge